test_p1 (__main__.Test.test_p1) ... ok
test_p10 (__main__.Test.test_p10) ... ok
test_p2 (__main__.Test.test_p2) ... FAIL
test_p3 (__main__.Test.test_p3) ... ok
test_p4 (__main__.Test.test_p4) ... ok
test_p5 (__main__.Test.test_p5) ... ERROR
test_p6 (__main__.Test.test_p6) ... ERROR
test_p7 (__main__.Test.test_p7) ... ERROR
test_p8 (__main__.Test.test_p8) ... ERROR
test_p9 (__main__.Test.test_p9) ... ERROR

======================================================================
ERROR: test_p5 (__main__.Test.test_p5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Bartosz\prg-basics\Testt\grade-test2-ZICSS1-1111.py", line 33, in test_p5
    import p5
ModuleNotFoundError: No module named 'p5'

======================================================================
ERROR: test_p6 (__main__.Test.test_p6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Bartosz\prg-basics\Testt\grade-test2-ZICSS1-1111.py", line 40, in test_p6
    import p6
ModuleNotFoundError: No module named 'p6'

======================================================================
ERROR: test_p7 (__main__.Test.test_p7)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Bartosz\prg-basics\Testt\grade-test2-ZICSS1-1111.py", line 47, in test_p7
    import p7
ModuleNotFoundError: No module named 'p7'

======================================================================
ERROR: test_p8 (__main__.Test.test_p8)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Bartosz\prg-basics\Testt\grade-test2-ZICSS1-1111.py", line 54, in test_p8
    import p8
ModuleNotFoundError: No module named 'p8'

======================================================================
ERROR: test_p9 (__main__.Test.test_p9)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Bartosz\prg-basics\Testt\grade-test2-ZICSS1-1111.py", line 59, in test_p9
    import p9
ModuleNotFoundError: No module named 'p9'

======================================================================
FAIL: test_p2 (__main__.Test.test_p2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Bartosz\prg-basics\Testt\grade-test2-ZICSS1-1111.py", line 19, in test_p2
    self.assertEqual(p2.f(30,90),178)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
AssertionError: 1779979416005228418 != 178

----------------------------------------------------------------------
Ran 10 tests in 0.014s

FAILED (failures=1, errors=5)
